[tool.poetry]
name = "face-reidentification"
version = "0.1.0"
description = ""
authors = ["Koter Michal <s24569@pjwstk.edu.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
